MakingMagicHappen/MakingMagicHappen/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView
from django.contrib.auth import views as auth_views

urlpatterns = [
	path('', include('rabbit.urls')),
    path(r'^home/$', TemplateView.as_view(template_name='rabbit/home.html'), name='home'),	
    path(r'^login/$', auth_views.LoginView.as_view(template_name = 'rabbit/login.html'), name='login'),
    path(r'^admin/', admin.site.urls),
	path(r'logout/', auth_views.LogoutView.as_view(), name='logout'),
]

MakingMagicHappen/rabbit/urls.py
from django.contrib import admin
from django.views.generic.edit import CreateView
from django.contrib.auth.forms import UserCreationForm
from django.urls import path
from django.conf.urls import url
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views
from django.contrib.auth.decorators import login_required
from django.views.generic.base import TemplateView
app_name = 'rabbit'

urlpatterns = [
	url(r'^$', TemplateView.as_view(template_name='rabbit/home.html'), name='home'),
    url(r'^about/$', TemplateView.as_view(template_name='rabbit/aboutUs.html'), name='about'),
    url(r'^login/$', auth_views.LoginView.as_view(template_name = 'rabbit/login.html'), name='login'),
    url(r'^adopt/$', TemplateView.as_view(template_name='rabbit/adopt.html'), name='adopt'),
    url(r'^rabbits/$', views.rabbit_views.as_view(), name='rabbits'),
    path('rabbits/bunnyprofile/<int:id>/', views.eachRabbit, name='bunnyprofile'),
    url(r'^guniea/$', views.guniea_views.as_view(), name='guniea'),
    path('guniea/gunieaprofile/<int:id>/', views.eachGuniea, name='gunieaprofile'),
    url(r'^careinfo/$', TemplateView.as_view(template_name='rabbit/careinfo.html'), name='careinfo'),
    url(r'^donate/$', TemplateView.as_view(template_name='rabbit/donate.html'), name='donate'),
    url(r'^calendar/$', TemplateView.as_view(template_name='rabbit/calendar.html'), name='calendar'),
    url(r'^deleting/$', login_required(views.usernameList), name='deleting'),
    url('submission/', login_required(views.submission), name='submission'),
    url(r'^volunteer/$', TemplateView.as_view(template_name='rabbit/volunteer.html'), name='volunteer'),
    path('rabbit/userDeleting/<int:id>/', login_required(views.userDelete),name='deleteUser'),
    path('rabbit/userChanging/<int:id>/', login_required(views.changingUserInfo),name='changingUserInfo'),
    url('post/new/', login_required(views.register), name='register'),
    path('contact/', views.emailService, name='contact'),
    url('post/new/', views.register, name='register'),
]

MakingMagicHappen/rabbit/models.py
from django.db import models
from django.conf import settings

# Create your models here.
# model for the calendar event
class calendarEvent(models.Model):
    user= models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    event_name = models.CharField(max_length= 100, null= False)
    event_time = models.TimeField((u"event Time"), auto_now_add=True, blank=True)
    event_location = models.CharField(max_length = 1000, null= False)


# model for the rabbit profile
class rabbitProfile(models.Model):
    name = models.CharField(max_length= 42, blank= False)
    Breed = models.CharField(max_length= 30)
    Gender = models.CharField(max_length= 6)
    Age = models.CharField(max_length= 10)
    Size = models.CharField(max_length= 10)
    Spayed_Neutered = models.CharField(max_length=5)
    Location = models.CharField(max_length=300, default='')
    about = models.TextField()
    profile_createdDate = models.DateTimeField(auto_now_add=True)
    image = models.CharField(max_length=400)

class gunieaProfile(models.Model):
    name = models.CharField(max_length= 42, blank= False)
    Breed = models.CharField(max_length= 30)
    Gender = models.CharField(max_length= 6)
    Age = models.CharField(max_length= 10)
    Size = models.CharField(max_length= 10)
    Spayed_Neutered = models.CharField(max_length=5)
    Location = models.CharField(max_length=300, default='')
    about = models.TextField()
    profile_createdDate = models.DateTimeField(auto_now_add=True)
    image = models.CharField(max_length=400)

MakingMagicHappen/rabbit/forms.py
from django import forms
from django.contrib.auth.models import User 





class newUserForm(forms.Form): 
    username = forms.CharField(max_length = 150, required = True) 
    password = forms.CharField(max_length = 128, required = True,widget=forms.PasswordInput()) 
    email = forms.EmailField(max_length = 254, required = True) 
    first_name = forms.CharField(max_length = 30, required = False) 
    last_name = forms.CharField(max_length = 150, required = False)
    is_superuser = forms.BooleanField(required=False)

class changingUserInfoForm(forms.Form): 
    username = forms.CharField(max_length = 150, required = False) 
    password = forms.CharField(max_length = 128, required = False,widget=forms.PasswordInput())
    email = forms.EmailField(max_length = 254, required = False) 
    first_name = forms.CharField(max_length = 30, required = False) 
    last_name = forms.CharField(max_length = 150, required = False)
    is_superuser = forms.BooleanField(required=False)
#Enter Your Name
#Enter email address
#Enter your Subject
#Message
class EmailServiceForm(forms.Form):
    your_Email = forms.EmailField(required=True)
    subject = forms.CharField(required=True)
    message = forms.CharField(widget=forms.Textarea, required=True)

SIZE_CHOICES = [('Small','Small'),('Medium', 'Medium'),('Large','Large')]
AGE_CHOICES = [('Young','Young'),('Adult', 'Adult')]
GENDER_CHOICES = [('Male','Male'),('Female', 'Female')]
FIXED_CHOICES = [('Yes','Yes'),('No', 'No')]
ANIMAL_CHOICES = [('Rabbit','Rabbit'),('Guinea Pig', 'Guinea Pig')]

class rabbitSubmissionForm(forms.Form):

    
    Species = forms.CharField( widget = forms.RadioSelect(choices =ANIMAL_CHOICES))
    Name = forms.CharField()
    Breed = forms.CharField()
    Gender = forms.CharField( widget = forms.RadioSelect(choices =GENDER_CHOICES))
    
    Age = forms.CharField( widget = forms.RadioSelect(choices =AGE_CHOICES))
    Size = forms.CharField( widget = forms.RadioSelect(choices =SIZE_CHOICES))#forms.CharField(required = False)
    Spayed_Neutered = forms.CharField( widget = forms.RadioSelect(choices =FIXED_CHOICES))
    Location = forms.CharField(max_length=300)
    About = forms.CharField(widget=forms.Textarea)
    # image = forms.ImageField()


    

MakingMagicHappen/rabbit/views.py
from django.shortcuts import render_to_response, render, redirect
from django.views import generic
import os, re
from django.conf import settings
from django.contrib.auth.models import User
from .forms import EmailServiceForm, newUserForm, changingUserInfoForm, rabbitSubmissionForm
from .models import rabbitProfile, gunieaProfile
from django.views.generic import FormView, TemplateView
from django.http import JsonResponse, HttpResponseRedirect
from django.core.mail import BadHeaderError, send_mail
from django.http import HttpResponse, HttpResponseRedirect

# Create your views here.
def home(request):
    return render_to_response('rabbit/home.html')

def login(request):
    return render(request,'rabbit/login.html')

def calendar(request):
    return render(request, 'rabbit/calendar.html')

# view for the registeration page
# data from the frontend is access using the newUserform
# validate the from and save the entered data in the user table  
def register(request):
    form = newUserForm(request.POST or None)
    if form.is_valid():
        print(form.cleaned_data)
        newUser = User(**form.cleaned_data)
        newUser.save()
        return redirect('/post/new/')
    context = {
        "form" : form
    }
    return render(request, 'rabbit/register.html', context)

# changing the data from the exixting user account

def changingUserInfo(request, id):
    user = User.objects.get(id=id)
    form = changingUserInfoForm(request.POST or None, initial={
        'username' : user.username,
        'password' : user.password,
        'email'    : user.email,
        'first_name' : user.first_name,
        'last_name' : user.last_name,
        'is_superuser' : user.is_superuser
    })
    if form.is_valid():
        user = User(id = id, **form.cleaned_data)
        user.save()
        return redirect("/post/new/")
    context = {
        "changingForm" : form,
        "user" : user
    }
    return render(request, 'rabbit/changing.html', context)


def usernameList(request):
    queryset = User.objects.all()
    context = {
        "object_list" : queryset
    }
    return render(request, 'rabbit/deleting.html', context)

def userDelete(request, id):
    user = User.objects.get(id=id)
    if request.method == "POST":
        user.delete()
        return redirect('/post/new/')
    context = {
        "user": user
    }
    return render(request,'rabbit/deleteUser.html',context)

def about(request):
    return render(request, 'rabbit/aboutUs.html')

# rabbit view will get all the rabbit info from the rabbitProfile
# modle and we can acceaa the object as all_rabbit_list from rabbits.html page 
class rabbit_views(generic.ListView):
    template_name='rabbit/rabbits.html'
    context_object_name = 'all_rabbit_list'
    queryset = rabbitProfile.objects.all()


# I should be able to  access each rabbit profile from bunnyprofile.html
def eachRabbit(request,id):
    rabbit = rabbitProfile.objects.get(id = id)
    if request.method == "POST":
        return redirect('/post/new/')
    context ={
        'rabbit' : rabbit
    }
    return render(request, 'rabbit/bunnyprofile.html', context)

#  view will get all the rabbit info from the rabbitProfile
# modle and we can acceaa the object as all_rabbit_list from rabbits.html page 
class guniea_views(generic.ListView):
    template_name='rabbit/gunieapigs.html'
    context_object_name = 'all_guniea_list'
    queryset = gunieaProfile.objects.all()


# I should be able to  access each rabbit profile from bunnyprofile.html
def eachGuniea(request,id):
    guniea = gunieaProfile.objects.get(id = id)
    if request.method == "POST":
        return redirect('/post/new/')
    context ={
        'guniea' : guniea
    }
    return render(request, 'rabbit/gunieaprofile.html', context)


#Enter email address
#Enter your Subject
#Message
def emailService(request):
    if request.method == 'GET':
        form = EmailServiceForm
    else:
        form = EmailServiceForm(request.POST)
        if form.is_valid():
            subject = form.cleaned_data['subject']
            from_email = form.cleaned_data['from_email']
            message = form.cleaned_data['message']
            try:
                send_mail(subject, message, from_email,['bistaaliza@gmail.com'])
            except BadHeaderError:
                return HttpResponse('Invalid header found.')
            return redirect('/contact')
    return render(request, "rabbit/contact.html", {'form':form})


def submission(request):
    form = rabbitSubmissionForm(request.POST)
    if form.is_valid():
        image = 'static/img/dbpic/'+ (re.sub('[^A-Za-z0-9]+','',form.cleaned_data['Name'])).lower()+ '.jpg'
        if form.cleaned_data['Species'].lower() == 'rabbit':
            rabbit = rabbitProfile(name = form.cleaned_data['Name'],
                                    Breed = form.cleaned_data['Breed'],
                                    Gender = form.cleaned_data['Gender'],
                                    Age = form.cleaned_data['Age'],
                                    Size = form.cleaned_data['Size'],
                                    Spayed_Neutered = form.cleaned_data['Spayed_Neutered'],
                                    Location = form.cleaned_data['Location'],
                                    about = form.cleaned_data['About'],
                                    image = image)
            rabbit.save()
            print('datasaved')
        else:
            gunieapig = gunieaProfile(name = form.cleaned_data['Name'],
                                    Breed = form.cleaned_data['Breed'],
                                    Gender = form.cleaned_data['Gender'],
                                    Age = form.cleaned_data['Age'],
                                    Size = form.cleaned_data['Size'],
                                    Spayed_Neutered = form.cleaned_data['Spayed_Neutered'],
                                    Location = form.cleaned_data['Location'],
                                    about = form.cleaned_data['About'],
                                    image = image)
            gunieapig.save()
        # rabbit = rabbitProfile(**form.cleaned_data)
        # rabbit.save()
        return redirect('./')
    context = {
        "form" : form
    }
    return render(request, 'rabbit/submission.html', context)

MakingMagicHappen/rabbit/templates/rabbit/base.html
<!DOCTYPE html>
<html lang="zxx" class="no-js">
<head>
    {% load static %}
    <!-- Mobile Specific Meta -->
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Favicon-->
    <!-- Meta Description -->
    <meta name="description" content="">
    <!-- Meta Keyword -->
    <meta name="keywords" content="">
    <!-- meta character set -->
    <meta charset="UTF-8">
    <!-- Site Title -->
    <title>Magic Happens Rabbit Rescue</title>
    <link href="https://fonts.googleapis.com/css?family=Poppins:100,200,400,300,500,600,700" rel="stylesheet"> 
    <!--
			CSS
            ============================================= -->
			<link rel="stylesheet" type="text/css" href="{% static 'css/linearicons.css' %}">
			<link rel="stylesheet" type="text/css" href="{% static 'css/font-awesome.min.css' %}">
			<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}">
			<link rel="stylesheet" type="text/css" href="{% static 'css/magnific-popup.css' %}">
			<link rel="stylesheet" type="text/css" href="{% static 'css/nice-select.css' %}">							
			<link rel="stylesheet" type="text/css" href="{% static 'css/animate.min.css' %}">
			<link rel="stylesheet" type="text/css" href="{% static 'css/owl.carousel.css' %}">
      <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
      <link href="{% static 'css/calendar.css' %}" rel="stylesheet" id="bootstrap-css">
      {% block csslink%}
      {% endblock csslink %}
        </head>
        <body>
            <header id="header" id="home">
              <div class="container main-menu">
                  <div class="row align-items-center justify-content-between d-flex">
                    <div id="logo">
                      <a href="home.html"><img src="{% static 'img/Making_Magic_Happen_Logo.png' %}" alt="" title="" /></a>
                    </div>
                    <nav id="nav-menu-container">
                      <ul class="nav-menu">
                        <li class="menu-active"><a href="{%url 'rabbit:home'%}">Home</a></li>
                        <li><a href="{%url 'rabbit:donate'%}">Donate</a></li>
                        <li><a href="{%url 'rabbit:about' %}">About Us</a></li>                        

                        <li><a href="{% url 'rabbit:calendar'%}">Calendar</a></li>
                        <li><a href="{% url 'rabbit:volunteer'%}">Volunteer</a></li>
                         <li class="menu-has-children"><a href="{% url 'rabbit:adopt'%}">Adopt</a> 
                          <ul>
                            <li><a href="{%url 'rabbit:rabbits'%}">Rabbits</a></li>
                            <li><a href="{%url 'rabbit:guniea'%}">Guinea Pigs</a></li>
                          </ul>

                        </li>
                        <li><a href="{%url 'rabbit:contact'%}">Contact</a></li>
                        {% if user.is_authenticated %}
                          {% if user.is_superuser%}
                            <li><a href="{% url 'rabbit:register' %}"> Register User </a></li>
                          {% endif %}
                          <li><a href="{% url 'rabbit:submission' %}"> Form Submission </a></li>
                          <li class = "menu-has-children"><a href="#">{{user.username}} </a>
                            <ul>
                              <li><a href="{% url 'logout' %}">
                                  <span class="no-icon">Log out </span>
                                </a>
                              </li>
                            </ul>
                          </li>
                        {% else %}
                          <li><a href="{%url 'rabbit:login'%}"> login </a></li>
                        {% endif %} 
                        </ul>
                      
                    
                    </nav><!-- #nav-menu-container -->	    		
                  </div>
              </div>
            </header><!-- #header -->
            {% block content %}
            {% endblock %}
<!-- Start calltoaction Area -->
<section class="calltoaction-area section-gap relative">
    <div class="container">
        <div class="overlay overlay-bg"></div>						
        <div class="row align-items-center justify-content-center">
            <h1 class="text-white">Want to help? Become a Volunteer!</h1>
            <br><br>
            <p class="text-white">
               Learn more about how you can help the rabbits at Magic Happens Rabbit Rescue today and learn how you can help make
               every rabbit's day a little bit brighter!
            </p>
            <br>
            <div class="buttons d-flex flex-row">
                
                <!--TODO: ADD LINK TO VOLUNTEER -->
                <a href="https://docs.google.com/forms/d/e/1FAIpQLSeuIWqnyVNOCnCMQaVRv1gaWtnigNYtISz1t2TDUHBp-N2mEA/viewform?c=0&w=1" class="primary-btn text-uppercase">Register!</a>
                <a href="{% url 'rabbit:volunteer' %}" class="primary-btn text-uppercase">Learn More</a>
            </div>
        </div>
    </div>	
</section>
<!-- End calltoaction Area -->


            <footer class="footer-area">
                <div class="container">
                    <div class="row pt-120 pb-80">
                      <div class="col-lg-4 col-md-6">
                        <div class="single-footer-widget">
                          <h6>About Us</h6>
                          <p>
                            Magic Happens is a network of volunteers centered in Baton Rouge, LA, and serves LA, MS, and occasionally other states. As a non-profit 501(c)3 organization, our mission is to rescue & find loving homes for rabbits that are at animal control facilities, abandoned or turned loose, or are unwanted by their owners. We also work hard to educate and serve our community through presentations and educational booths at events so that rabbits & owners will have a happier & healthier life together.
                          </p>
                        </div>
                      </div>
                      <div class="col-lg-4 col-md-6">
                        <div class="single-footer-widget">
                          <h6>Useful Links</h6>
                          <div class="row">
                            <ul class="col footer-nav">
                              <li><a href="{%url 'rabbit:home'%}">Home</a></li>
                              <li><a href="{%url 'rabbit:donate'%}">Donate</a></li>
                              <li><a href="{%url 'rabbit:about' %}">About Us</a></li>
                              <li><a href="{% url 'rabbit:careinfo' %}">Care Info</a></li>
                            </ul>
                            <ul class="col footer-nav">
                              <li><a href="{% url 'rabbit:calendar'%}">Calendar</a></li>
                              <li><a href="{% url 'rabbit:adopt'%}">Adopt</a></li>
                              <li><a href="{% url 'rabbit:volunteer'%}">Volunteer</a></li>
                            </ul>									
                          </div>
                        </div>
                      </div>						
                      <div class="col-lg-4  col-md-6">
                        <div class="single-footer-widget mail-chimp">
                          <h6 class="mb-20">Contact Us</h6>
                          <ul class="list-contact">
                            <li class="flex-row d-flex">
                              <div class="icon">
                                <span class="lnr lnr-home"></span>
                              </div>
                              <div class="detail">
                                <h4>Baton Rouge, LA</h4>
                                <p>
                                  <!--4343 Hinkle Deegan Lake Road-->
                                </p>
                              </div>	
                            </li>
                            <li class="flex-row d-flex">
                              <div class="icon">
                                <span class="lnr lnr-phone-handset"></span>
                              </div>
                              <div class="detail">
                                <h4>(225)  341 - 2866</h4>
                                <p>
                                  <!--Mon to Fri 9am to 7 pm-->
                                </p>
                              </div>	
                            </li>
                            <li class="flex-row d-flex">
                              <div class="icon">
                                <span class="lnr lnr-envelope"></span>
                              </div>
                              <div class="detail">
                                <h4>wendy@magichappensrescue.com</h4>
                                <p>
                                  <!--Send us your query anytime!-->
                                </p>
                              </div>	
                            </li>																		
                          </ul>
                        </div>
                      </div>						
                    </div>
                  </div>
                  <div class="container">
                      <div class="row footer-bottom d-flex justify-content-between">
                          <p class="col-lg-8 col-sm-6 footer-text m-0 text-white">
                          <div class="col-lg-4 col-sm-6 footer-social">
                              <a href="https://www.facebook.com/magichappensrescue"><i class="fa fa-facebook"></i></a>
                              <a href="https://www.facebook.com/honeybadgerbunny"><i class="fa fa-twitter"></i></a>
                              <a href="https://www.instagram.com/magichappensrabbitrescue/"><i class="fa fa-instagram"></i></a>
                              <a href="https://www.pinterest.com/magichappensres/"><i class="fa fa-pinterest"></i></a>
                          </div>
                      </div>						
                  </div>
              </div>
          </footer>
          <!-- End footer Area -->	

          <script src="{% static 'js/vendor/jquery-2.2.4.min.js' %}"></script>
          <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
          <script src="{% static 'js/vendor/bootstrap.min.js' %}"></script>			
          <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBhOdIF3Y9382fqJYt5I_sswSrEw5eihAA"></script>
          <script src="{% static 'js/easing.min.js' %}"></script>			
          <script src="{% static 'js/hoverIntent.js' %}"></script>
          <script src="{% static 'js/superfish.min.js' %}"></script>	
          <script src="{% static 'js/jquery.ajaxchimp.min.js' %}"></script>
          <script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>	
          <script src="{% static 'js/owl.carousel.min.js' %}"></script>						
          <script src="{% static 'js/jquery.nice-select.min.js' %}"></script>	
          <script src="{% static 'js/main.js' %}"></script>	
          {% block scriptlink %}
          {% endblock scriptlink %}

          {% block ajax %}
          {% endblock %}
      </body>
  </html>

MakingMagicHappen/rabbit/templates/rabbit/calendar.html
{% extends 'rabbit/base.html' %}
    {% load static %}
    {% block csslink %}
    <!-- <link href="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css"> -->
    <!-- <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script> -->
    <script src="http://code.jquery.com/jquery-1.11.1.min.js">
    </script>
    <!-- <link href="https://fonts.googleapis.com/css?family=Roboto:100,100i,300,300i,400,400i,500,500i,700,700i,900,900i" rel="stylesheet"> -->

<script>
    $(document).ready(function() {
    var date = new Date();
    var d = date.getDate();
    var m = date.getMonth();
    var y = date.getFullYear();
    
    /*  className colors
    
    className: default(transparent), important(red), chill(pink), success(green), info(blue)
    
    */		
    
      
    /* initialize the external events
    -----------------------------------------------------------------*/


    /* initialize the calendar
    -----------------------------------------------------------------*/
    
    var calendar =  $('#calendar').fullCalendar({
        header: {
            left: 'title',
            center: 'agendaDay,agendaWeek,month',
            right: 'prev,next today'
        },
        editable: true,
        firstDay: 1, //  1(Monday) this can be changed to 0(Sunday) for the USA system
        selectable: true,
        defaultView: 'month',
        
        axisFormat: 'h:mm',
        columnFormat: {
            month: 'ddd',    // Mon
            week: 'ddd d', // Mon 7
            day: 'dddd M/d',  // Monday 9/7
            agendaDay: 'dddd d'
        },
        titleFormat: {
            month: 'MMMM yyyy', // September 2009
            week: "MMMM yyyy", // September 2009
            day: 'MMMM yyyy'                  // Tuesday, Sep 8, 2009
        },
        allDaySlot: false,
        selectHelper: true,
        select: function(start, end, allDay) {
            var title = prompt('Event Title:');
            if (title) {
                calendar.fullCalendar('renderEvent',
                    {
                        title: title,
                        start: start,
                        end: end,
                        allDay: allDay
                    },
                    true // make the event "stick"
                );
            }
            calendar.fullCalendar('unselect');
        },
        droppable: true, // this allows things to be dropped onto the calendar !!!
        drop: function(date, allDay) { // this function is called when something is dropped
        
            // retrieve the dropped element's stored Event Object
            var originalEventObject = $(this).data('eventObject');
            
            // we need to copy it, so that multiple events don't have a reference to the same object
            var copiedEventObject = $.extend({}, originalEventObject);
            
            // assign it the date that was reported
            copiedEventObject.start = date;
            copiedEventObject.allDay = allDay;
            
            // render the event on the calendar
            // the last `true` argument determines if the event "sticks" (http://arshaw.com/fullcalendar/docs/event_rendering/renderEvent/)
            $('#calendar').fullCalendar('renderEvent', copiedEventObject, true);
            
            // is the "remove after drop" checkbox checked?
            if ($('#drop-remove').is(':checked')) {
                // if so, remove the element from the "Draggable Events" list
                $(this).remove();
            }
            
        },
        
        events: [
            {
                title: 'All Day Event',
                start: new Date(y, m, 5)
            },
            {
                id: 999,
                title: 'Repeating Event',
                start: new Date(y, m, d-7, 16, 0),
                allDay: false,
                className: 'info'
            },
            {
                id: 999,
                title: 'Repeating Event',
                start: new Date(y, m, d+8, 16, 0),
                allDay: true,
                className: 'info'
            },
            {
                title: 'Meeting',
                start: new Date(y, m, d, 14, 30),
                allDay: false,
                className: 'important'
            },
            {
                title: 'Rabbit care',
                start: new Date(y, m, 28),
                end: new Date(y, m, 29),
                url: 'https://ccp.cloudaccess.net/aff.php?aff=5188',
                className: 'success'
            }
        ],			
    });
    
    
});

</script>
<style>
    #calendar {
        /* 		float: right; */
        margin: 0px auto;
        width: 800px;
        background-color: #FFFFFF;
        border-radius: 6px;
        box-shadow: 0 1px 2px #C3C3C3;
    }
</style>
{% endblock csslink %}
{% block content %}
 
<section class="banner-area relative" id="home">	
    <div class="overlay overlay-bg"></div>
    <div class="container">				
        <div class="row d-flex align-items-center justify-content-center">
            <div class="about-content col-lg-12">
                <h1 class="text-white">
                    Calendar				
                </h1>	
                <p class="text-white link-nav"><a href="{% url 'rabbit:home'%}">Home </a>  <span class="lnr lnr-arrow-right"></span>  <a href="{% url 'rabbit:calendar' %}"> Calendar</a></p>
            </div>	
        </div>
    </div>
</section>
<!-- End banner Area -->
<section class="home-about-area">
    <div class="container-fluid">
        <div class="row align-items-center">	
            <div class="col-lg-6 home-about-left no-padding">
                <div class="container">
                <div class="overlay overlay-bg"></div>
                    <div id='calendar' style="margin-top: 100px; margin-left: 150px"></div>											
                </div>
            </div>
        </div>
    </div>	
</section>
<br>
<br>
<br>
<br>
    {% endblock %}

    {% block scriptlink %}
    <script src="{% static 'js/calendar.js'%}"></script>
    {% endblock scriptlink %}

MakingMagicHappen/rabbit/templates/rabbit/login.html
{% extends 'rabbit/login_base.html' %}
{% block content %}
	{% include 'rabbit/includes/login_form.html' %}
{% endblock %}

MakingMagicHappen/rabbit/templates/rabbit/login_base.html
<!DOCTYPE html>
<html>
	<head>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	{% load static %}
	<link rel="stylesheet" type="text/css" href="{% static 'css/login_style.css' %}" />
	<body>
		{% block content %}
		{% endblock %}
	</body>
</html>